language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1

before_install:
  - composer install
  - pip install --user codecov

after_success:
  - codecov

sudo: false

git:
  submodules: true

before_script:
  - pecl install runkit
  - phpenv config-add .travis.php.ini
  - cd sql
  - bash test_db.sh 1
  - cd ..

script:
  - bash .travis.phplint.sh
  - phpunit --verbose --coverage-clover=coverage.xml
  - codecov

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikipedia-en-accounts-devs"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
