language: php

php:
  - 5.5
  - 5.6
  
matrix:
  allow_failures:
    - php: 5.6

before_install:
  - pip install --user codecov

after_success:
  - codecov

sudo: false

git:
  submodules: true

before_script:
  - cd sql
  - bash test_db.sh 1
  - cd ..

script:
  - bash .travis.phplint.sh
  - phpunit

#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#wikipedia-en-accounts-devs"
#    on_success: change
#    on_failure: always
#    template:
#      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
