language: php

php:
  - 7.3

addons:
  mariadb: '10.2'

os: linux
dist: bionic

before_install:
  - composer install

git:
  submodules: true

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root MYSQL_SCHEMA=testdb

before_script:
  - pecl install runkit7-3.0.0
  - phpenv config-add .travis.php.ini
  - cd sql
  - bash test_db.sh 1
  - cd ..

script:
  - bash .travis.phplint.sh
  - bash .travis.scss.sh
  - php vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikipedia-en-accounts-devs"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
